### ISSUE TITLE
No support for hitArea?

### ISSUE THREAD

**Issue by jbockmon** [kittykatattack/bump#13]
I am not sure if this is a bug with bump.js or Sprite.hitArea.

According to doc at: http://pixijs.download/release/docs/PIXI.Sprite.html#hitArea if a Sprite has been assigned a hitArea, Bound checking will check the hitArea instead of Bounds. After assigning a hitArea to a sprite, bump.js reacts to the Bounds, and not hitArea.

**Comment by kittykatattack** [comment]
That's correct, Bump does not use Pixis `hitArea` for collision detection.
