### ISSUE TITLE
Still maintained?

### ISSUE THREAD

**Issue by rowild** [kittykatattack/bump#21]
You mention a new version, when PIXI 4 comes out... which has. Are you still maintaining the lib? Or has Bump2 (https://github.com/LCluber/Bump.js) become the follower?

Would be great if you could mention something in the ReadMe! Thank you!

**Comment by MH15** [comment]
There's a fork of this library [here](https://github.com/lycwed/pixi-plugin-bump) that has been updated more recently.

**Comment by rowild** [comment]
@MH15 Thank you!

**Comment by AdrienLemaire** [comment]
@kittykatattack @lycwed do you have plans to upgrade your bump library to support Pixijs v5 ?

**Comment by lycwed** [comment]
Unnfortunately no @AdrienLemaire, now I prefered use quadtree lib like [this one](https://github.com/CorentinTh/quadtree-js).

**Comment by AdrienLemaire** [comment]
Lovely, thanks for the quick reply and link !
