### ISSUE TITLE
Deprecation Warning: The ParticleContainer class has been moved to particles.ParticleContainer, please use particles.ParticleContainer from now on

### ISSUE THREAD

**Issue by happierall** [kittykatattack/bump#7]
PIXI.js v4

**Comment by kittykatattack** [comment]
Thank you for reporting this, I'll sort this out on the next major update

**Comment by crazyyi** [comment]
Also some of the PIXI.Sprite's methods has changed. There is no `getGlobalPosition` method in PIXI.Sprite or its parent classes.

**Comment by kittykatattack** [comment]
@crazyyi Do you happen to know what the replacement for `getGlobalPosition` is?

**Comment by crazyyi** [comment]
@kittykatattack Oops sorry I just found it in libs/extras.getGlobalPosition.js. It says it is a member of DisplayObject class but this function is not in the documentation so I thought it didn't exist. My bad.

**Comment by kittykatattack** [comment]
@crazyyi No problem, thanks for letting know.
And thanks for using this library! 😄 I'm busy updating all these little Pixi helper libraries to Pixi v4.2.x over the next few weeks.
